### ISSUE TITLE
add replacements to nfpm

### ISSUE THREAD

**Issue by FalcoSuessgott** [FalcoSuessgott/golang-cli-template#13]
```
replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
```

and add example for downloading this
